// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "jabber_protocol.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * announce to everyone that this client supports jabber
 * also included are the username and the hash of the public key
 *
 * @generated from protobuf message JabberIdentify
 */
export interface JabberIdentify {
    /**
     * @generated from protobuf field: string username = 1
     */
    username: string;
    /**
     * @generated from protobuf field: bytes hash = 2
     */
    hash: Uint8Array;
}
/**
 * initiate handshake with jabber user
 *
 * @generated from protobuf message JabberHello
 */
export interface JabberHello {
    /**
     * @generated from protobuf field: JabberIdentify me = 3
     */
    me?: JabberIdentify;
    /**
     * @generated from protobuf field: bytes public_key = 4
     */
    publicKey: Uint8Array;
}
/**
 * finish handshake
 *
 * @generated from protobuf message JabberHelloResponse
 */
export interface JabberHelloResponse {
    /**
     * @generated from protobuf field: JabberIdentify me = 3
     */
    me?: JabberIdentify;
    /**
     * @generated from protobuf field: bytes encrypted_public_key = 5
     */
    encryptedPublicKey: Uint8Array;
}
/**
 * @generated from protobuf message JabberHandshakeReject
 */
export interface JabberHandshakeReject {
    /**
     * @generated from protobuf field: JabberIdentify me = 3
     */
    me?: JabberIdentify;
    /**
     * @generated from protobuf field: bytes public_key = 4
     */
    publicKey: Uint8Array;
}
// handshake example
// cassandra: username="cassandra" hash=0x1337... key=0xC...
// alice: username="alice" hash=0x80085... key=0xA...
// ^ alice is canonically a lesbian anyways
// 
// alice -> cassandra
// JabberHello {
// JabberIdentify me {
// username = "alice"
// hash = 0x80085
// }
// public_key = 0xA...
// }
// 
// cassandra encrypts her key with alice's key
// cassandra -> alice
// JabberHelloResponse {
// JabberIdentify me {
// username = "cassandra"
// hash = 0x1337
// }
// encrypted_public_key = ...
// }
// 
// alice decrypts cassandras key
// all is good
// 

// message JabberMessage {}

/**
 * @generated from protobuf message JabberMessagePacket
 */
export interface JabberMessagePacket {
    /**
     * @generated from protobuf field: bytes encrypted_message = 6
     */
    encryptedMessage: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class JabberIdentify$Type extends MessageType<JabberIdentify> {
    constructor() {
        super("JabberIdentify", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "hash", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<JabberIdentify>): JabberIdentify {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.username = "";
        message.hash = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<JabberIdentify>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JabberIdentify): JabberIdentify {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string username */ 1:
                    message.username = reader.string();
                    break;
                case /* bytes hash */ 2:
                    message.hash = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JabberIdentify, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string username = 1; */
        if (message.username !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.username);
        /* bytes hash = 2; */
        if (message.hash.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.hash);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message JabberIdentify
 */
export const JabberIdentify = new JabberIdentify$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JabberHello$Type extends MessageType<JabberHello> {
    constructor() {
        super("JabberHello", [
            { no: 3, name: "me", kind: "message", T: () => JabberIdentify },
            { no: 4, name: "public_key", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<JabberHello>): JabberHello {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.publicKey = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<JabberHello>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JabberHello): JabberHello {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* JabberIdentify me */ 3:
                    message.me = JabberIdentify.internalBinaryRead(reader, reader.uint32(), options, message.me);
                    break;
                case /* bytes public_key */ 4:
                    message.publicKey = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JabberHello, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* JabberIdentify me = 3; */
        if (message.me)
            JabberIdentify.internalBinaryWrite(message.me, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bytes public_key = 4; */
        if (message.publicKey.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.publicKey);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message JabberHello
 */
export const JabberHello = new JabberHello$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JabberHelloResponse$Type extends MessageType<JabberHelloResponse> {
    constructor() {
        super("JabberHelloResponse", [
            { no: 3, name: "me", kind: "message", T: () => JabberIdentify },
            { no: 5, name: "encrypted_public_key", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<JabberHelloResponse>): JabberHelloResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.encryptedPublicKey = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<JabberHelloResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JabberHelloResponse): JabberHelloResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* JabberIdentify me */ 3:
                    message.me = JabberIdentify.internalBinaryRead(reader, reader.uint32(), options, message.me);
                    break;
                case /* bytes encrypted_public_key */ 5:
                    message.encryptedPublicKey = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JabberHelloResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* JabberIdentify me = 3; */
        if (message.me)
            JabberIdentify.internalBinaryWrite(message.me, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bytes encrypted_public_key = 5; */
        if (message.encryptedPublicKey.length)
            writer.tag(5, WireType.LengthDelimited).bytes(message.encryptedPublicKey);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message JabberHelloResponse
 */
export const JabberHelloResponse = new JabberHelloResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JabberHandshakeReject$Type extends MessageType<JabberHandshakeReject> {
    constructor() {
        super("JabberHandshakeReject", [
            { no: 3, name: "me", kind: "message", T: () => JabberIdentify },
            { no: 4, name: "public_key", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<JabberHandshakeReject>): JabberHandshakeReject {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.publicKey = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<JabberHandshakeReject>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JabberHandshakeReject): JabberHandshakeReject {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* JabberIdentify me */ 3:
                    message.me = JabberIdentify.internalBinaryRead(reader, reader.uint32(), options, message.me);
                    break;
                case /* bytes public_key */ 4:
                    message.publicKey = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JabberHandshakeReject, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* JabberIdentify me = 3; */
        if (message.me)
            JabberIdentify.internalBinaryWrite(message.me, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bytes public_key = 4; */
        if (message.publicKey.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.publicKey);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message JabberHandshakeReject
 */
export const JabberHandshakeReject = new JabberHandshakeReject$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JabberMessagePacket$Type extends MessageType<JabberMessagePacket> {
    constructor() {
        super("JabberMessagePacket", [
            { no: 6, name: "encrypted_message", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<JabberMessagePacket>): JabberMessagePacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.encryptedMessage = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<JabberMessagePacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JabberMessagePacket): JabberMessagePacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes encrypted_message */ 6:
                    message.encryptedMessage = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JabberMessagePacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes encrypted_message = 6; */
        if (message.encryptedMessage.length)
            writer.tag(6, WireType.LengthDelimited).bytes(message.encryptedMessage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message JabberMessagePacket
 */
export const JabberMessagePacket = new JabberMessagePacket$Type();
