// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "protocol.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// 
// export type PacketType =
// 'DataReceive' |
// 'ClientList' |
// 'DataSend' |
// 'ClientListRequest' |
// 'BadPacket' |
// 'UnknownReciever'
// export interface Packet {
// type: PacketType
// }
// // Server -> Client
// export interface DataReceivePacket extends Packet {
// type: 'DataReceive'
// data: string
// from: number
// }
// export interface ClientListPacket extends Packet {
// type: 'ClientList'
// clients: number[]
// }
// export interface BadPacketPacket extends Packet {
// type: 'BadPacket'
// }
// export interface UnknownRecieverPacket extends Packet {
// type: 'UnknownReciever'
// }
// // Client -> Server
// export interface DataSendPacket extends Packet {
// type: 'DataSend'
// data: string
// to: number
// }
// export interface ClientListRequestPacket extends Packet {
// type: 'ClientListRequest'
// }

/**
 * Server -> Client
 *
 * @generated from protobuf message DataReceivePacket
 */
export interface DataReceivePacket {
    /**
     * @generated from protobuf field: bytes data = 1
     */
    data: Uint8Array;
    /**
     * @generated from protobuf field: uint32 from = 2
     */
    from: number;
}
/**
 * @generated from protobuf message ClientListPacket
 */
export interface ClientListPacket {
    /**
     * @generated from protobuf field: repeated uint32 clients = 3
     */
    clients: number[];
}
/**
 * @generated from protobuf message BadPacketPacket
 */
export interface BadPacketPacket {
}
/**
 * @generated from protobuf message UnknownRecieverPacket
 */
export interface UnknownRecieverPacket {
}
/**
 * @generated from protobuf message IdentityPacket
 */
export interface IdentityPacket {
    /**
     * @generated from protobuf field: uint32 you = 2
     */
    you: number;
    /**
     * @generated from protobuf field: repeated uint32 clients = 3
     */
    clients: number[];
}
/**
 * Client -> Server
 *
 * @generated from protobuf message DataSendPacket
 */
export interface DataSendPacket {
    /**
     * @generated from protobuf field: bytes data = 1
     */
    data: Uint8Array;
    /**
     * @generated from protobuf field: uint32 to = 2
     */
    to: number;
}
/**
 * @generated from protobuf message ClientListRequestPacket
 */
export interface ClientListRequestPacket {
}
// @generated message type with reflection information, may provide speed optimized methods
class DataReceivePacket$Type extends MessageType<DataReceivePacket> {
    constructor() {
        super("DataReceivePacket", [
            { no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "from", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<DataReceivePacket>): DataReceivePacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = new Uint8Array(0);
        message.from = 0;
        if (value !== undefined)
            reflectionMergePartial<DataReceivePacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DataReceivePacket): DataReceivePacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes data */ 1:
                    message.data = reader.bytes();
                    break;
                case /* uint32 from */ 2:
                    message.from = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DataReceivePacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes data = 1; */
        if (message.data.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.data);
        /* uint32 from = 2; */
        if (message.from !== 0)
            writer.tag(2, WireType.Varint).uint32(message.from);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DataReceivePacket
 */
export const DataReceivePacket = new DataReceivePacket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientListPacket$Type extends MessageType<ClientListPacket> {
    constructor() {
        super("ClientListPacket", [
            { no: 3, name: "clients", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ClientListPacket>): ClientListPacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clients = [];
        if (value !== undefined)
            reflectionMergePartial<ClientListPacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientListPacket): ClientListPacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated uint32 clients */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.clients.push(reader.uint32());
                    else
                        message.clients.push(reader.uint32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClientListPacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated uint32 clients = 3; */
        if (message.clients.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.clients.length; i++)
                writer.uint32(message.clients[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ClientListPacket
 */
export const ClientListPacket = new ClientListPacket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BadPacketPacket$Type extends MessageType<BadPacketPacket> {
    constructor() {
        super("BadPacketPacket", []);
    }
    create(value?: PartialMessage<BadPacketPacket>): BadPacketPacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<BadPacketPacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BadPacketPacket): BadPacketPacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BadPacketPacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message BadPacketPacket
 */
export const BadPacketPacket = new BadPacketPacket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnknownRecieverPacket$Type extends MessageType<UnknownRecieverPacket> {
    constructor() {
        super("UnknownRecieverPacket", []);
    }
    create(value?: PartialMessage<UnknownRecieverPacket>): UnknownRecieverPacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UnknownRecieverPacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnknownRecieverPacket): UnknownRecieverPacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnknownRecieverPacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message UnknownRecieverPacket
 */
export const UnknownRecieverPacket = new UnknownRecieverPacket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentityPacket$Type extends MessageType<IdentityPacket> {
    constructor() {
        super("IdentityPacket", [
            { no: 2, name: "you", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "clients", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<IdentityPacket>): IdentityPacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.you = 0;
        message.clients = [];
        if (value !== undefined)
            reflectionMergePartial<IdentityPacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentityPacket): IdentityPacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 you */ 2:
                    message.you = reader.uint32();
                    break;
                case /* repeated uint32 clients */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.clients.push(reader.uint32());
                    else
                        message.clients.push(reader.uint32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentityPacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 you = 2; */
        if (message.you !== 0)
            writer.tag(2, WireType.Varint).uint32(message.you);
        /* repeated uint32 clients = 3; */
        if (message.clients.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.clients.length; i++)
                writer.uint32(message.clients[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message IdentityPacket
 */
export const IdentityPacket = new IdentityPacket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataSendPacket$Type extends MessageType<DataSendPacket> {
    constructor() {
        super("DataSendPacket", [
            { no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "to", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<DataSendPacket>): DataSendPacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = new Uint8Array(0);
        message.to = 0;
        if (value !== undefined)
            reflectionMergePartial<DataSendPacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DataSendPacket): DataSendPacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes data */ 1:
                    message.data = reader.bytes();
                    break;
                case /* uint32 to */ 2:
                    message.to = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DataSendPacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes data = 1; */
        if (message.data.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.data);
        /* uint32 to = 2; */
        if (message.to !== 0)
            writer.tag(2, WireType.Varint).uint32(message.to);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message DataSendPacket
 */
export const DataSendPacket = new DataSendPacket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientListRequestPacket$Type extends MessageType<ClientListRequestPacket> {
    constructor() {
        super("ClientListRequestPacket", []);
    }
    create(value?: PartialMessage<ClientListRequestPacket>): ClientListRequestPacket {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ClientListRequestPacket>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClientListRequestPacket): ClientListRequestPacket {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ClientListRequestPacket, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ClientListRequestPacket
 */
export const ClientListRequestPacket = new ClientListRequestPacket$Type();
